import csv
import io
import os
from datetime import datetime
from functools import wraps

from dotenv import load_dotenv
from flask import Flask, Response, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from flask_limiter import Limiter 
from flask_limiter.util import get_remote_address
import warnings
from db import get_conn, get_cursor
from migrations import (
    ensure_audit_table,
    ensure_audit_triggers,
    ensure_db_constraints,
    ensure_db_functions,
    ensure_db_procedures,
    ensure_db_views,
    ensure_project_name_column,
)

load_dotenv()

_ADMIN_PASSWORD_HASH = generate_password_hash(os.getenv("ADMIN_PASSWORD", "owner123"))

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev-secret-change-me")

# -------------------------- 
# Rate limiter 
# -------------------------- 

warnings.filterwarnings("ignore", category=UserWarning)
#The warning generated by this has no impact on the app,
#just mentioning that this will not work properly when app
#is hosted on multiple servers (which it will not be)

def get_user_key(): 
    return session.get("user_id") or get_remote_address() 
    
limiter = Limiter( 
    key_func=get_user_key, 
    app=app, 
    default_limits=["20 per second"] 
)

# --------------------------
# Helpers
# --------------------------

def ensure_password_column_size():
    """
    Ensure User_tbl.Password can store hashed passwords.
    Older schema versions use VARCHAR(50), which truncates hashes.
    """
    try:
        with get_conn() as conn:
            cur = conn.cursor(dictionary=True)
            cur.execute(
                """
                SELECT CHARACTER_MAXIMUM_LENGTH AS max_len
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = 'User_tbl'
                  AND COLUMN_NAME = 'Password'
                """
            )
            row = cur.fetchone()
            if row and row.get("max_len") and int(row["max_len"]) < 255:
                cur.execute("ALTER TABLE User_tbl MODIFY Password VARCHAR(255) NOT NULL")
            cur.close()
    except Exception as exc:
        app.logger.warning("Could not verify/upgrade User_tbl.Password column: %s", exc)


def ensure_company_auth_table():
    """
    Ensure company auth-code table exists for gated self-registration.
    Auth codes are stored hashed.
    """
    try:
        with get_conn() as conn:
            cur = conn.cursor(dictionary=True)
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS CompanyAuthCode (
                    CompanyID VARCHAR(50) PRIMARY KEY,
                    AuthCodeHash VARCHAR(255) NOT NULL,
                    CONSTRAINT fk_company_auth_company
                      FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
                      ON DELETE CASCADE
                )
                """
            )
            cur.close()
    except Exception as exc:
        app.logger.warning("Could not verify/create CompanyAuthCode table: %s", exc)


_password_column_checked = False
_company_auth_table_checked = False
_migrations_run = False


@app.before_request
def _ensure_password_column_once():
    if request.path == "/health":
        return
    global _password_column_checked, _company_auth_table_checked, _migrations_run
    if _password_column_checked:
        if not _company_auth_table_checked:
            _company_auth_table_checked = True
            ensure_company_auth_table()
        return
    _password_column_checked = True
    _company_auth_table_checked = True
    ensure_password_column_size()
    ensure_company_auth_table()
    if not _migrations_run:
        _migrations_run = True
        ensure_project_name_column()
        ensure_db_functions()
        ensure_db_constraints()
        ensure_db_procedures()
        ensure_db_views()
        ensure_audit_table()
        ensure_audit_triggers()


def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if session.get("user_id") is None:
            flash("Please log in first.", "warning")
            return redirect(url_for("login"))
        return view(*args, **kwargs)

    return wrapped


def admin_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if not session.get("is_admin"):
            flash("Please log in as admin first.", "warning")
            return redirect(url_for("admin_login"))
        return view(*args, **kwargs)

    return wrapped


@app.before_request
def load_logged_in_user():
    g.user = {
        "user_id": session.get("user_id"),
        "company_id": session.get("company_id"),
        "username": session.get("username"),
        "company_name": session.get("company_name"),
    }


def next_id(cursor, table, column, prefix, digits=3):
    cursor.execute(f"LOCK TABLES {table} WRITE")
    cursor.execute(f"SELECT MAX({column}) AS max_id FROM {table}")
    row = cursor.fetchone()
    max_id = row["max_id"] if row else None
    if not max_id:
        return f"{prefix}{1:0{digits}d}"
    n = int(str(max_id)[len(prefix):]) + 1
    return f"{prefix}{n:0{digits}d}"


def to_bool(value):
    return str(value).lower() in {"1", "true", "on", "yes"}


def safe_date(value):
    if not value:
        return None
    try:
        return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError:
        return None


_FIELD_MAX_LENGTHS = {
    "username": 50, "password": 255, "company_id": 6, "company_name": 100,
    "employee_name": 50, "project_name": 100, "site_name": 50, "location": 100,
}


def validate_lengths(**fields):
    """Return an error string if any field exceeds its DB column length, else None."""
    for field, value in fields.items():
        max_len = _FIELD_MAX_LENGTHS.get(field)
        if max_len and value and len(str(value)) > max_len:
            label = field.replace("_", " ").title()
            return f"{label} must be {max_len} characters or fewer."
    return None


def is_invalid_date_range(start_date, end_date):
    return bool(start_date and end_date and end_date < start_date)


def safe_float(value, default=None):
    try:
        return float(value) if value not in (None, "") else default
    except (TypeError, ValueError):
        return default


def parse_report_params():
    return {
        "report_type": request.args.get("type", "hours_by_site"),
        "start_date": request.args.get("start_date", ""),
        "end_date": request.args.get("end_date", ""),
        "employee_id": request.args.get("employee_id", ""),
        "site_id": request.args.get("site_id", ""),
        "hourly_rate": safe_float(request.args.get("hourly_rate"), 40.0),
    }


def load_report_filters(cur, company_id):
    cur.execute("SELECT EmployeeID, Name FROM Employee WHERE CompanyID=%s ORDER BY Name", (company_id,))
    employees_list = cur.fetchall()
    cur.execute(
        "SELECT js.SiteID, js.SiteName FROM Job_site js JOIN Project p ON p.ProjectID = js.ProjectID WHERE p.CompanyID=%s ORDER BY js.SiteName",
        (company_id,),
    )
    sites = cur.fetchall()
    return employees_list, sites


def fetch_report_rows(cur, company_id, report_type, start_date, end_date, employee_id, site_id, hourly_rate, default_to_pay_by_site=False):
    start_date = start_date or None
    end_date = end_date or None
    employee_id = employee_id or None
    site_id = site_id or None
    
    if not (start_date and end_date):
        return []

    if report_type == "hours_by_site":
        cur.execute(
            """
            SELECT js.SiteName, p.ProjectID, SUM(tc.Hours) AS TotalHours,
                   COUNT(DISTINCT tc.EmployeeID) AS NumEmployees
            FROM Timecard tc
            JOIN Schedule s ON s.ScheduleID = tc.ScheduleID
            JOIN Job_site js ON js.SiteID = s.SiteID
            JOIN Project p ON p.ProjectID = js.ProjectID
            JOIN Employee e ON e.EmployeeID = tc.EmployeeID
            WHERE e.CompanyID = %s AND tc.Date BETWEEN %s AND %s
            GROUP BY js.SiteName, p.ProjectID
            ORDER BY js.SiteName
            """,
            (company_id, start_date, end_date),
        )
        return cur.fetchall()

    if report_type == "employee_hours":
        cur.execute(
            "CALL GetReports(%s, %s, %s, %s)",
            (company_id, start_date, end_date, employee_id if employee_id else None),
        )
        return cur.fetchall()

    if report_type == "pay_by_site" or default_to_pay_by_site:
        cur.execute(
            "CALL generate_report(%s, %s, %s, %s, %s, %s)",
            (
                company_id,
                start_date,
                end_date,
                employee_id if employee_id else None,
                site_id if site_id else None,
                hourly_rate,
            ),
        )
        return cur.fetchall()

    return []


def authenticate_user(username, password):
    with get_cursor() as cur:
        cur.execute("CALL login(%s)", (username,))
        user = cur.fetchone()

    if not user:
        return None

    stored = user["Password"]

    valid = check_password_hash(stored, password)
    return user if valid else None


def authenticate_admin(username, password):
    expected_username = os.getenv("ADMIN_USERNAME", "owner")
    return username == expected_username and check_password_hash(_ADMIN_PASSWORD_HASH, password)


# --------------------------
# Auth
# --------------------------
@app.route("/health")
def health():
    return "ok", 200


@app.route("/")
def index():
    if session.get("is_admin"):
        return redirect(url_for("admin_companies"))
    return redirect(url_for("dashboard") if session.get("user_id") else url_for("login"))


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        user = authenticate_user(username, password)
        if user:
            session.clear()
            session["user_id"] = user["UserID"]
            session["company_id"] = user["CompanyID"]
            session["username"] = user["Username"]
            session["company_name"] = user["CompanyName"]
            flash("Logged in successfully.", "success")
            return redirect(url_for("dashboard"))
        flash("Invalid username or password.", "danger")
    return render_template("login.html")


@app.route("/register", methods=["GET", "POST"])
def register():
    with get_cursor() as cur:
        cur.execute("SELECT CompanyID, CompanyName FROM Company ORDER BY CompanyName")
        companies = cur.fetchall()

    if request.method == "POST":
        company_id = request.form.get("company_id", "").strip()
        company_auth_code = request.form.get("company_auth_code", "")
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        confirm = request.form.get("confirm_password", "")

        if password != confirm:
            flash("Passwords do not match.", "danger")
            return render_template("register.html", companies=companies)

        if len(password) < 8:
            flash("Password must be at least 8 characters.", "danger")
            return render_template("register.html", companies=companies)

        err = validate_lengths(username=username)
        if err:
            flash(err, "danger")
            return render_template("register.html", companies=companies)

        with get_conn() as conn:
            cur = conn.cursor(dictionary=True)
            cur.execute("SELECT AuthCodeHash FROM CompanyAuthCode WHERE CompanyID = %s", (company_id,))
            auth_row = cur.fetchone()
            if not auth_row or not check_password_hash(auth_row["AuthCodeHash"], company_auth_code):
                flash("Invalid company auth code.", "danger")
                cur.close()
                return render_template("register.html", companies=companies)

            cur.execute("SELECT COUNT(*) AS cnt FROM User_tbl WHERE Username = %s", (username,))
            if cur.fetchone()["cnt"] > 0:
                flash("Username already exists.", "danger")
                cur.close()
                return render_template("register.html", companies=companies)

            user_id = next_id(cur, "User_tbl", "UserID", "USR", 3)
            hashed = generate_password_hash(password)
            cur.execute("UNLOCK TABLES")
            cur.execute(
                "CALL create_account(%s, %s, %s, %s)",
                (user_id, company_id, username, hashed),
            )
            cur.close()

        flash("Account created. Please log in.", "success")
        return redirect(url_for("login"))

    return render_template("register.html", companies=companies)


@app.route("/logout")
def logout():
    session.clear()
    flash("Logged out.", "info")
    return redirect(url_for("login"))


# --------------------------
# Admin
# --------------------------
@app.route("/admin/login", methods=["GET", "POST"])
def admin_login():
    if session.get("is_admin"):
        return redirect(url_for("admin_companies"))

    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        if authenticate_admin(username, password):
            session.clear()
            session["is_admin"] = True
            session["admin_username"] = username
            flash("Admin login successful.", "success")
            return redirect(url_for("admin_companies"))
        flash("Invalid admin credentials.", "danger")

    return render_template("admin_login.html")


@app.route("/admin/companies")
@admin_required
def admin_companies():
    with get_cursor() as cur:
        cur.execute(
            """
            SELECT c.CompanyID, c.CompanyName,
                   CASE WHEN cac.CompanyID IS NULL THEN 0 ELSE 1 END AS HasAuthCode
            FROM Company c
            LEFT JOIN CompanyAuthCode cac ON cac.CompanyID = c.CompanyID
            ORDER BY c.CompanyName
            """
        )
        companies = cur.fetchall()
    return render_template("admin_companies.html", companies=companies)


@app.route("/admin/companies/add", methods=["POST"])
@admin_required
def admin_add_company():
    company_id = request.form.get("company_id", "").strip()
    company_name = request.form.get("company_name", "").strip()
    company_auth_code = request.form.get("company_auth_code", "")

    if not company_id or not company_name or not company_auth_code:
        flash("Company ID, Company Name, and Auth Code are required.", "danger")
        return redirect(url_for("admin_companies"))

    err = validate_lengths(company_id=company_id, company_name=company_name)
    if err:
        flash(err, "danger")
        return redirect(url_for("admin_companies"))

    with get_conn() as conn:
        cur = conn.cursor(dictionary=True)
        cur.execute("SELECT COUNT(*) AS cnt FROM Company WHERE CompanyID=%s", (company_id,))
        if cur.fetchone()["cnt"] > 0:
            cur.close()
            flash("Company ID already exists.", "danger")
            return redirect(url_for("admin_companies"))
        cur.execute("INSERT INTO Company (CompanyID, CompanyName) VALUES (%s, %s)", (company_id, company_name))
        cur.execute(
            "INSERT INTO CompanyAuthCode (CompanyID, AuthCodeHash) VALUES (%s, %s)",
            (company_id, generate_password_hash(company_auth_code)),
        )
        cur.close()

    flash("Company created.", "success")
    return redirect(url_for("admin_companies"))


@app.route("/admin/companies/<company_id>/edit", methods=["POST"])
@admin_required
def admin_edit_company(company_id):
    company_name = request.form.get("company_name", "").strip()
    company_auth_code = request.form.get("company_auth_code", "")
    if not company_name:
        flash("Company Name is required.", "danger")
        return redirect(url_for("admin_companies"))

    with get_conn() as conn:
        cur = conn.cursor(dictionary=True)
        cur.execute("UPDATE Company SET CompanyName=%s WHERE CompanyID=%s", (company_name, company_id))
        if company_auth_code:
            cur.execute(
                """
                INSERT INTO CompanyAuthCode (CompanyID, AuthCodeHash)
                VALUES (%s, %s)
                ON DUPLICATE KEY UPDATE AuthCodeHash = VALUES(AuthCodeHash)
                """,
                (company_id, generate_password_hash(company_auth_code)),
            )
        cur.close()
    flash("Company updated.", "success")
    return redirect(url_for("admin_companies"))


@app.route("/admin/companies/<company_id>/delete", methods=["POST"])
@admin_required
def admin_delete_company(company_id):
    try:
        with get_cursor() as cur:
            cur.execute("DELETE FROM Company WHERE CompanyID=%s", (company_id,))
        flash("Company deleted.", "info")
    except Exception:
        flash("Could not delete company. It may still be referenced by users or records.", "danger")
    return redirect(url_for("admin_companies"))


# --------------------------
# Dashboard
# --------------------------
@app.route("/dashboard")
@login_required
def dashboard():
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute("CALL ActiveEmployees(%s)", (company_id,))
        active_employees = cur.fetchone()["cnt"]

    with get_cursor() as cur:
        cur.execute("CALL ActiveTimecards(%s)", (company_id,))
        active_timecards = cur.fetchone()["cnt"]

    with get_cursor() as cur:
        cur.execute("CALL ActiveProjects(%s)", (company_id,))
        active_projects = cur.fetchone()["cnt"]

    with get_cursor() as cur:
        cur.execute(
            "SELECT PayrollID, PeriodStart, PeriodEnd FROM Payroll WHERE CompanyID=%s ORDER BY PeriodEnd DESC LIMIT 1",
            (company_id,),
        )
        latest_payroll = cur.fetchone()
        cur.execute("SELECT TradeID, TradeName FROM Trade ORDER BY TradeName")
        trades = cur.fetchall()
        cur.execute("SELECT UnionID, UnionName FROM Union_tbl ORDER BY UnionName")
        unions = cur.fetchall()

    return render_template(
        "dashboard.html",
        active_employees=active_employees,
        active_timecards=active_timecards,
        active_projects=active_projects,
        latest_payroll=latest_payroll,
        trades=trades,
        unions=unions,
    )


# --------------------------
# Employees
# --------------------------
@app.route("/employees")
@login_required
def employees():
    company_id = session["company_id"]
    search = request.args.get("search", "").strip()
    active = request.args.get("active", "")

    search_param = search if search else None
    active_param = int(active) if active in {"0", "1"} else None

    with get_cursor() as cur:
        cur.execute("SELECT TradeID, TradeName FROM Trade ORDER BY TradeName")
        trades = cur.fetchall()
        cur.execute("SELECT UnionID, UnionName FROM Union_tbl ORDER BY UnionName")
        unions = cur.fetchall()
        cur.execute("CALL GetEmployees(%s, %s, %s)", (company_id, search_param, active_param))
        employees = cur.fetchall()

    return render_template("employees.html", employees=employees, trades=trades, unions=unions)


@app.route("/employees/add", methods=["POST"])
@login_required
def add_employee():
    company_id = session["company_id"]
    name = request.form.get("name", "").strip()
    err = validate_lengths(employee_name=name)
    if err:
        flash(err, "danger")
        return redirect(url_for("employees"))
    with get_conn() as conn:
        cur = conn.cursor(dictionary=True)
        employee_id = next_id(cur, "Employee", "EmployeeID", "E", 5)
        cur.execute(
            "CALL add_employee(%s, %s, %s, %s, %s, %s)",
            (
                employee_id,
                company_id,
                request.form.get("union_id") or None,
                request.form.get("trade_id"),
                name,
                to_bool(request.form.get("active")),
            ),
        )
        cur.execute("UNLOCK TABLES")
        cur.close()
    flash("Employee added.", "success")
    return redirect(url_for("employees"))


@app.route("/employees/<employee_id>/edit", methods=["POST"])
@login_required
def edit_employee(employee_id):
    company_id = session["company_id"]
    name = request.form.get("name", "").strip()
    err = validate_lengths(employee_name=name)
    if err:
        flash(err, "danger")
        return redirect(url_for("employees"))
    with get_cursor() as cur:
        cur.execute("SELECT 1 FROM Employee WHERE EmployeeID=%s AND CompanyID=%s", (employee_id, company_id))
        if not cur.fetchone():
            flash("Employee not found.", "danger")
            return redirect(url_for("employees"))
        cur.execute(
            "CALL edit_employee(%s, %s, %s, %s, %s)",
            (
                employee_id,
                name,
                request.form.get("union_id") or None,
                request.form.get("trade_id"),
                to_bool(request.form.get("active")),
            ),
        )
    flash("Employee updated.", "success")
    return redirect(url_for("employees"))


@app.route("/employees/<employee_id>/delete", methods=["POST"])
@login_required
def delete_employee(employee_id):
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute("SELECT 1 FROM Employee WHERE EmployeeID=%s AND CompanyID=%s", (employee_id, company_id))
        if not cur.fetchone():
            flash("Employee not found.", "danger")
            return redirect(url_for("employees"))
        cur.execute("CALL delete_employee(%s)", (employee_id,))
    flash("Employee deleted.", "info")
    return redirect(url_for("employees"))


# --------------------------
# Projects / Job sites
# --------------------------
@app.route("/projects")
@login_required
def projects():
    company_id = session["company_id"]
    status = request.args.get("status", "")
    search = request.args.get("search", "").strip()

    search_param = search if search else None
    status_param = int(status) if status in {"0", "1"} else None

    with get_cursor() as cur:
        cur.execute("CALL DisplayProjects(%s, %s, %s)", (company_id, search_param, status_param))
        projects = cur.fetchall()

    return render_template("projects.html", projects=projects, search=search)


@app.route("/projects/add", methods=["POST"])
@login_required
def add_project():
    company_id = session["company_id"]
    project_name = request.form.get("project_name", "").strip()
    err = validate_lengths(project_name=project_name)
    if err:
        flash(err, "danger")
        return redirect(url_for("projects"))
    with get_conn() as conn:
        cur = conn.cursor(dictionary=True)
        project_id = next_id(cur, "Project", "ProjectID", "P", 5)
        cur.execute(
            "CALL add_project(%s, %s, %s, %s)",
            (project_id, company_id, project_name, to_bool(request.form.get("status"))),
        )
        cur.execute("UNLOCK TABLES")
        cur.close()
    flash("Project added.", "success")
    return redirect(url_for("projects"))


@app.route("/projects/<project_id>/edit", methods=["POST"])
@login_required
def edit_project(project_id):
    company_id = session["company_id"]
    project_name = request.form.get("project_name", "").strip()
    err = validate_lengths(project_name=project_name)
    if err:
        flash(err, "danger")
        return redirect(url_for("projects"))
    with get_cursor() as cur:
        cur.execute("SELECT 1 FROM Project WHERE ProjectID=%s AND CompanyID=%s", (project_id, company_id))
        if not cur.fetchone():
            flash("Project not found.", "danger")
            return redirect(url_for("projects"))
        cur.execute(
            "CALL sp_edit_project(%s, %s, %s)",
            (project_id, to_bool(request.form.get("status")), project_name),
        )
    flash("Project updated.", "success")
    return redirect(url_for("projects"))


@app.route("/projects/<project_id>/delete", methods=["POST"])
@login_required
def delete_project(project_id):
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute("SELECT 1 FROM Project WHERE ProjectID=%s AND CompanyID=%s", (project_id, company_id))
        if not cur.fetchone():
            flash("Project not found.", "danger")
            return redirect(url_for("projects"))
        cur.execute("CALL delete_project(%s)", (project_id,))
    flash("Project deleted.", "info")
    return redirect(url_for("projects"))


@app.route("/sites")
@login_required
def sites():
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute(
            """
            SELECT js.SiteID, js.ProjectID, js.SiteName, js.Location
            FROM Job_site js
            JOIN Project p ON p.ProjectID = js.ProjectID
            WHERE p.CompanyID = %s
            ORDER BY js.SiteName
            """,
            (company_id,),
        )
        all_sites = cur.fetchall()
        cur.execute(
            "SELECT ProjectID, ProjectName FROM Project WHERE CompanyID=%s ORDER BY ProjectID",
            (company_id,),
        )
        projects = cur.fetchall()
    return render_template("sites.html", sites=all_sites, projects=projects)


@app.route("/sites/add", methods=["POST"])
@login_required
def add_site():
    company_id = session["company_id"]
    project_id = request.form.get("project_id")
    site_name = request.form.get("site_name", "").strip()
    location = request.form.get("location", "").strip()
    err = validate_lengths(site_name=site_name, location=location)
    if err:
        flash(err, "danger")
        return redirect(url_for("sites"))
    with get_conn() as conn:
        cur = conn.cursor(dictionary=True)
        cur.execute("SELECT 1 FROM Project WHERE ProjectID=%s AND CompanyID=%s", (project_id, company_id))
        if not cur.fetchone():
            cur.close()
            flash("Invalid project for this company.", "danger")
            return redirect(url_for("projects"))
        site_id = next_id(cur, "Job_site", "SiteID", "S", 5)
        cur.execute(
            "INSERT INTO Job_site (SiteID, ProjectID, SiteName, Location) VALUES (%s, %s, %s, %s)",
            (site_id, project_id, site_name, location),
        )
        cur.execute("UNLOCK TABLES")
        cur.close()
    flash("Job site added.", "success")
    return redirect(url_for("sites"))


@app.route("/sites/<site_id>/edit", methods=["POST"])
@login_required
def edit_site(site_id):
    company_id = session["company_id"]
    new_project_id = request.form.get("project_id")
    site_name = request.form.get("site_name", "").strip()
    location = request.form.get("location", "").strip()
    err = validate_lengths(site_name=site_name, location=location)
    if err:
        flash(err, "danger")
        return redirect(url_for("sites"))
    with get_cursor() as cur:
        cur.execute("SELECT 1 FROM Project WHERE ProjectID=%s AND CompanyID=%s", (new_project_id, company_id))
        if not cur.fetchone():
            flash("Invalid project for this company.", "danger")
            return redirect(url_for("sites"))
        cur.execute("SELECT 1 FROM Job_site WHERE SiteID=%s AND ProjectID IN (SELECT ProjectID FROM Project WHERE CompanyID=%s)", (site_id, company_id))
        if not cur.fetchone():
            flash("Site not found.", "danger")
            return redirect(url_for("sites"))
        cur.execute(
            "CALL edit_job_site(%s, %s, %s, %s)",
            (site_id, new_project_id, site_name, location),
        )
    flash("Job site updated.", "success")
    return redirect(url_for("sites"))


@app.route("/sites/<site_id>/delete", methods=["POST"])
@login_required
def delete_site(site_id):
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute(
            "DELETE FROM Job_site WHERE SiteID=%s AND ProjectID IN (SELECT ProjectID FROM Project WHERE CompanyID=%s)",
            (site_id, company_id),
        )
    flash("Job site deleted.", "info")
    return redirect(url_for("sites"))


# --------------------------
# Assignments / schedules
# --------------------------
@app.route("/assignments")
@login_required
def assignments():
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute(
            "SELECT EmployeeID, Name FROM Employee WHERE CompanyID=%s ORDER BY Name",
            (company_id,),
        )
        employees = cur.fetchall()

        cur.execute(
            "SELECT js.SiteID, js.SiteName FROM Job_site js JOIN Project p ON p.ProjectID = js.ProjectID WHERE p.CompanyID=%s ORDER BY js.SiteName",
            (company_id,),
        )
        sites = cur.fetchall()

        cur.execute(
            """
            SELECT e.EmployeeID, e.Name AS EmployeeName, t.TradeName,
                   s.ScheduleID, js.SiteID, js.SiteName, p.ProjectID,
                   s.StartDate, s.EndDate, p.Status AS ProjectStatus
            FROM Schedule s
            JOIN Employee e ON e.EmployeeID = s.EmployeeID
            JOIN Trade t ON t.TradeID = e.TradeID
            JOIN Job_site js ON js.SiteID = s.SiteID
            JOIN Project p ON p.ProjectID = js.ProjectID
            WHERE p.CompanyID = %s
            ORDER BY e.Name, s.StartDate
            """,
            (company_id,),
        )
        assignments = cur.fetchall()

    return render_template("assignments.html", assignments=assignments, sites=sites, employees=employees)


@app.route("/assignments/add", methods=["POST"])
@login_required
def add_assignment():
    company_id = session["company_id"]

    employee_id = request.form.get("employee_id")
    site_id = request.form.get("site_id")
    start_date = safe_date(request.form.get("start_date"))
    end_date = safe_date(request.form.get("end_date"))

    if is_invalid_date_range(start_date, end_date):
        flash("End date cannot be before start date.", "danger")
        return redirect(url_for("assignments"))

    with get_conn() as conn:
        cur = conn.cursor(dictionary=True)

        schedule_id = next_id(cur, "Schedule", "ScheduleID", "SC", 4)
        cur.execute("UNLOCK TABLES")

        cur.execute(
            """
            INSERT INTO Schedule (ScheduleID, SiteID, EmployeeID, StartDate, EndDate)
            VALUES (%s, %s, %s, %s, %s)
            """,
            (schedule_id, site_id, employee_id, start_date, end_date),
        )

        cur.close()

    flash("Assignment created.", "success")
    return redirect(url_for("assignments"))

@app.route("/assignments/<schedule_id>/edit", methods=["POST"])
@login_required
def edit_assignment(schedule_id):
    company_id = session["company_id"]
    start_date = safe_date(request.form.get("start_date"))
    end_date = safe_date(request.form.get("end_date"))
    if is_invalid_date_range(start_date, end_date):
        flash("End date cannot be before start date.", "danger")
        return redirect(url_for("assignments"))
    with get_cursor() as cur:
        cur.execute(
            """
            UPDATE Schedule
            SET SiteID=%s, StartDate=%s, EndDate=%s
            WHERE ScheduleID=%s
              AND SiteID IN (
                  SELECT js.SiteID FROM Job_site js
                  JOIN Project p ON p.ProjectID = js.ProjectID
                  WHERE p.CompanyID=%s
              )
            """,
            (
                request.form.get("site_id"),
                start_date,
                end_date,
                schedule_id,
                company_id,
            ),
        )
    flash("Assignment updated.", "success")
    return redirect(url_for("assignments"))

@app.route("/assignments/<schedule_id>/delete", methods=["POST"])
@login_required
def delete_assignment(schedule_id):
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute(
            """
            SELECT 1 FROM Schedule s
            JOIN Job_site js ON js.SiteID = s.SiteID
            JOIN Project p ON p.ProjectID = js.ProjectID
            WHERE s.ScheduleID = %s AND p.CompanyID = %s
            """,
            (schedule_id, company_id),
        )
        if not cur.fetchone():
            flash("Assignment not found.", "danger")
            return redirect(url_for("assignments"))
        cur.execute("DELETE FROM Timecard WHERE ScheduleID=%s", (schedule_id,))
        cur.execute("DELETE FROM Schedule WHERE ScheduleID=%s", (schedule_id,))
    flash("Assignment deleted.", "info")
    return redirect(url_for("assignments"))


# --------------------------
# Timecards
# --------------------------
@app.route("/timecards")
@login_required
def timecards():
    company_id = session["company_id"]
    employee_id = request.args.get("employee_id", "").strip()
    work_date = request.args.get("date", "").strip()

    employee_id_param = employee_id if employee_id else None
    date_param = safe_date(work_date) if work_date else None

    with get_cursor() as cur:
        cur.execute("SELECT EmployeeID, Name FROM Employee WHERE CompanyID=%s ORDER BY Name", (company_id,))
        employees_list = cur.fetchall()

        cur.execute(
            """
            SELECT DISTINCT js.SiteID, js.SiteName
            FROM Job_site js
            JOIN Project p ON p.ProjectID = js.ProjectID
            WHERE p.CompanyID = %s
            ORDER BY js.SiteName
            """,
            (company_id,),
        )
        schedules = cur.fetchall()

    with get_cursor() as cur:
        cur.execute("CALL GetTimecards(%s, %s, %s)", (company_id, employee_id_param, date_param))
        timecards = cur.fetchall()

    return render_template(
        "timecards.html",
        timecards=timecards,
        employees=employees_list,
        schedules=schedules,
    )


@app.route("/timecards/add", methods=["POST"])
@login_required
def add_timecard():
    company_id = session["company_id"]
    with get_conn() as conn:
        cur = conn.cursor(dictionary=True)
        employee_id = request.form.get("employee_id")
        site_id = request.form.get("schedule_id")

        cur.execute("SELECT 1 FROM Employee WHERE EmployeeID=%s AND CompanyID=%s", (employee_id, company_id))
        if not cur.fetchone():
            cur.close()
            flash("Invalid employee for this company.", "danger")
            return redirect(url_for("timecards"))

        cur.execute(
            """
            SELECT s.ScheduleID FROM Schedule s
            JOIN Job_site js ON js.SiteID = s.SiteID
            JOIN Project p ON p.ProjectID = js.ProjectID
            WHERE s.SiteID = %s AND s.EmployeeID = %s AND p.CompanyID = %s
            LIMIT 1
            """,
            (site_id, employee_id, company_id),
        )
        schedule = cur.fetchone()
        if not schedule:
            cur.close()
            flash("No schedule found for this employee at that site.", "danger")
            return redirect(url_for("timecards"))

        hours = safe_float(request.form.get("hours"))
        if hours is None:
            cur.close()
            flash("Hours must be a valid number.", "danger")
            return redirect(url_for("timecards"))

        timecard_id = next_id(cur, "Timecard", "TimecardID", "TC", 4)
        cur.execute("UNLOCK TABLES")
        cur.execute(
            "CALL add_timecard(%s, %s, %s, %s, %s)",
            (
                timecard_id,
                schedule["ScheduleID"],
                employee_id,
                safe_date(request.form.get("date")),
                hours,
            ),
        )
        cur.close()
    flash("Timecard added.", "success")
    return redirect(url_for("timecards"))

@app.route("/timecards/<timecard_id>/edit", methods=["POST"])
@login_required
def edit_timecard(timecard_id):
    company_id = session["company_id"]
    employee_id = request.form.get("employee_id")
    site_id = request.form.get("schedule_id")

    with get_cursor() as cur:
        cur.execute(
            """
            SELECT s.ScheduleID FROM Schedule s
            JOIN Job_site js ON js.SiteID = s.SiteID
            JOIN Project p ON p.ProjectID = js.ProjectID
            WHERE s.SiteID = %s AND s.EmployeeID = %s AND p.CompanyID = %s
            LIMIT 1
            """,
            (site_id, employee_id, company_id),
        )
        schedule = cur.fetchone()
        if not schedule:
            flash("No schedule found for this employee at that site.", "danger")
            return redirect(url_for("timecards"))
    hours = safe_float(request.form.get("hours"))
    if hours is None:
        flash("Hours must be a valid number.", "danger")
        return redirect(url_for("timecards"))

    with get_cursor() as cur:
        cur.execute(
            """
            UPDATE Timecard
            SET ScheduleID=%s, EmployeeID=%s, Date=%s, Hours=%s
            WHERE TimecardID=%s
              AND EmployeeID IN (SELECT EmployeeID FROM Employee WHERE CompanyID=%s)
            """,
            (
                schedule["ScheduleID"],
                request.form.get("employee_id"),
                safe_date(request.form.get("date")),
                hours,
                timecard_id,
                company_id,
            ),
        )
    flash("Timecard updated.", "success")
    return redirect(url_for("timecards"))


@app.route("/timecards/<timecard_id>/delete", methods=["POST"])
@login_required
def delete_timecard(timecard_id):
    company_id = session["company_id"]
    with get_cursor() as cur:
        cur.execute(
            "SELECT 1 FROM Timecard tc JOIN Employee e ON e.EmployeeID = tc.EmployeeID WHERE tc.TimecardID=%s AND e.CompanyID=%s",
            (timecard_id, company_id),
        )
        if not cur.fetchone():
            flash("Timecard not found.", "danger")
            return redirect(url_for("timecards"))
        cur.execute(
            """
            SELECT pr.PayrollID FROM Payroll pr
            JOIN Timecard tc ON tc.Date BETWEEN pr.PeriodStart AND pr.PeriodEnd
            JOIN Employee e ON e.EmployeeID = tc.EmployeeID
            WHERE tc.TimecardID = %s AND pr.CompanyID = %s
            LIMIT 1
            """,
            (timecard_id, company_id),
        )
        if cur.fetchone():
            flash("Cannot delete a timecard that is part of a processed payroll.", "danger")
            return redirect(url_for("timecards"))
        cur.execute("CALL delete_timecard(%s)", (timecard_id,))
    flash("Timecard deleted.", "info")
    return redirect(url_for("timecards"))


# --------------------------
# Payroll
# --------------------------
@app.route("/payroll", methods=["GET", "POST"])
@login_required
def payroll():
    company_id = session["company_id"]

    if request.method == "POST":
        start_date = safe_date(request.form.get("start_date"))
        end_date = safe_date(request.form.get("end_date"))
        if is_invalid_date_range(start_date, end_date):
            flash("End date cannot be before start date.", "danger")
            return redirect(url_for("payroll"))
        hourly_rate = safe_float(request.form.get("hourly_rate"), 40.0)

        with get_conn() as conn:
            cur = conn.cursor(dictionary=True)
            payroll_id = next_id(cur, "Payroll", "PayrollID", "PR", 4)
            cur.execute(
                "INSERT INTO Payroll (PayrollID, CompanyID, PeriodStart, PeriodEnd) VALUES (%s, %s, %s, %s)",
                (payroll_id, company_id, start_date, end_date),
            )
            cur.execute("UNLOCK TABLES")
            cur.execute(
                "CALL run_payroll(%s, %s, %s, %s, %s)",
                (payroll_id, company_id, start_date, end_date, hourly_rate),
            )
            cur.close()
        flash("Payroll run completed.", "success")
        return redirect(url_for("payroll"))

    filter_start = safe_date(request.args.get("filter_start"))
    filter_end = safe_date(request.args.get("filter_end"))

    with get_cursor() as cur:
        cur.execute(
            "CALL GetPayroll(%s, %s, %s)",
            (company_id, filter_start or None, filter_end or None),
        )
        payrolls = cur.fetchall()
        for p in payrolls:
            p["total_gross"] = p["total_gross"] or 0
            p["total_net"] = p["total_net"] or 0
            p["total_hours"] = p["total_hours"] or 0

    return render_template(
        "payroll.html",
        payrolls=payrolls,
        filter_start=filter_start or "",
        filter_end=filter_end or "",
    )


# --------------------------
# Reports
# --------------------------
@app.route("/reports")
@login_required
def reports():
    company_id = session["company_id"]
    report_params = parse_report_params()
    report_type = report_params["report_type"]
    start_date = report_params["start_date"]
    end_date = report_params["end_date"]
    employee_id = report_params["employee_id"]
    site_id = report_params["site_id"]
    hourly_rate = report_params["hourly_rate"]

    if is_invalid_date_range(safe_date(start_date), safe_date(end_date)):
        flash("End date cannot be before start date.", "danger")
        return redirect(url_for("reports", type=report_type))

    with get_cursor() as cur:
        employees_list, sites = load_report_filters(cur, company_id)
        rows = fetch_report_rows(cur, company_id, report_type, start_date, end_date, employee_id, site_id, hourly_rate)

    return render_template(
        "reports.html",
        rows=rows,
        report_type=report_type,
        employees=employees_list,
        sites=sites,
        start_date=start_date,
        end_date=end_date,
        employee_id=employee_id,
        site_id=site_id,
        hourly_rate=hourly_rate,
    )


@app.route("/reports/export")
@login_required
def export_report():
    company_id = session["company_id"]
    report_params = parse_report_params()
    report_type = report_params["report_type"]
    start_date = report_params["start_date"]
    end_date = report_params["end_date"]
    employee_id = report_params["employee_id"]
    site_id = report_params["site_id"]
    hourly_rate = report_params["hourly_rate"]

    with get_cursor() as cur:
        rows = fetch_report_rows(cur, company_id, report_type, start_date, end_date, employee_id, site_id, hourly_rate)

    if not rows:
        flash("No data to export.", "warning")
        return redirect(url_for("reports", type=report_type, start_date=start_date, end_date=end_date,
                                employee_id=employee_id, site_id=site_id, hourly_rate=hourly_rate))

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)

    filename = f"report_{report_type}_{start_date}_{end_date}.csv"
    return Response(
        output.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


# --------------------------
# Change Password
# --------------------------
@app.route("/change_password", methods=["POST"])
@login_required
def change_password():
    referrer = request.form.get("_referrer") or url_for("dashboard")
    current_password = request.form.get("current_password", "")
    new_password = request.form.get("new_password", "")
    confirm = request.form.get("confirm_password", "")

    if new_password != confirm:
        flash("New passwords do not match.", "danger")
        return redirect(referrer)

    if len(new_password) < 8:
        flash("New password must be at least 8 characters.", "danger")
        return redirect(referrer)

    with get_cursor() as cur:
        cur.execute("CALL login(%s)", (session["username"],))
        user = cur.fetchone()

    if not user or not check_password_hash(user["Password"], current_password):
        flash("Current password is incorrect.", "danger")
        return redirect(referrer)

    new_hash = generate_password_hash(new_password)
    with get_cursor() as cur:
        cur.execute(
            "UPDATE User_tbl SET Password=%s WHERE UserID=%s",
            (new_hash, session["user_id"]),
        )
    flash("Password updated successfully.", "success")
    return redirect(url_for("dashboard"))


@app.errorhandler(Exception)
def handle_error(exc):
    app.logger.error("Unhandled exception: %s", exc, exc_info=True)
    return render_template("error.html"), 500


if __name__ == "__main__":
    app.run(debug=True)
